{"identifier":{"url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError\/Infinity","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Infinity"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore\/evaluationerror\/infinity"]}],"metadata":{"roleHeading":"Case","title":"EvaluationError.Infinity","externalID":"s:11SoulverCore15EvaluationErrorO8InfinityyA2CmF","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Infinity","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"SoulverCore"}]},"abstract":[{"type":"text","text":"Not really infinity, but a number too large for us to handle"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://app.soulver.core/documentation/SoulverCore":{"type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A powerful natural language calculation engine"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","url":"\/documentation\/soulvercore","title":"SoulverCore"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationError":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"EvaluationError","kind":"identifier"}],"title":"EvaluationError","type":"topic","role":"symbol","abstract":[{"text":"All errors that SoulverCore can produce as a result of a calculation","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"EvaluationError"}],"url":"\/documentation\/soulvercore\/evaluationerror"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationError/Infinity":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Not really infinity, but a number too large for us to handle"}],"title":"EvaluationError.Infinity","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"Infinity","kind":"identifier"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError\/Infinity","url":"\/documentation\/soulvercore\/evaluationerror\/infinity"}}}