{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult"]]},"metadata":{"roleHeading":"Case","externalID":"s:11SoulverCore16EvaluationResultO6failedyA2CmF","title":"EvaluationResult.failed","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"modules":[{"name":"SoulverCore"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore\/evaluationresult\/failed"]}],"abstract":[{"text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)","type":"text"}],"seeAlsoSections":[{"title":"Nil answer cases","identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)"],"generated":true}],"references":{"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult":{"abstract":[{"text":"Represents the underlying data of a result of a SoulverCore calculation","type":"text"}],"navigatorTitle":[{"text":"EvaluationResult","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EvaluationResult"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","type":"topic","title":"EvaluationResult","kind":"symbol","url":"\/documentation\/soulvercore\/evaluationresult"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/pending":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","url":"\/documentation\/soulvercore\/evaluationresult\/pending","abstract":[{"type":"text","text":"A result that must be fetched asyncronously (probably over a network)"}],"title":"EvaluationResult.pending"},"doc://app.soulver.core/documentation/SoulverCore":{"url":"\/documentation\/soulvercore","title":"SoulverCore","abstract":[{"text":"A powerful natural language calculation engine","type":"text"}],"role":"collection","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/error(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11SoulverCore15EvaluationErrorO","text":"EvaluationError"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)","url":"\/documentation\/soulvercore\/evaluationresult\/error(_:)","abstract":[],"title":"EvaluationResult.error(_:)"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/none":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","url":"\/documentation\/soulvercore\/evaluationresult\/none","abstract":[{"type":"text","text":"A null result"}],"title":"EvaluationResult.none"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/failed":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","url":"\/documentation\/soulvercore\/evaluationresult\/failed","abstract":[{"type":"text","text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)"}],"title":"EvaluationResult.failed"}}}