{"kind":"symbol","abstract":[{"type":"text","text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)"}],"seeAlsoSections":[{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)"],"generated":true,"title":"Nil answer cases"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore\/evaluationresult\/failed"]}],"metadata":{"externalID":"s:11SoulverCore16EvaluationResultO6failedyA2CmF","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"role":"symbol","roleHeading":"Case","title":"EvaluationResult.failed","modules":[{"name":"SoulverCore"}],"symbolKind":"case"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed"},"sections":[],"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult"]]},"references":{"doc://app.soulver.core/documentation/SoulverCore":{"title":"SoulverCore","type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","url":"\/documentation\/soulvercore","abstract":[{"text":"A powerful natural language calculation engine","type":"text"}],"role":"collection","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/pending":{"title":"EvaluationResult.pending","kind":"symbol","url":"\/documentation\/soulvercore\/evaluationresult\/pending","abstract":[{"type":"text","text":"A result that must be fetched asyncronously (probably over a network)"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"pending","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/none":{"title":"EvaluationResult.none","kind":"symbol","url":"\/documentation\/soulvercore\/evaluationresult\/none","abstract":[{"type":"text","text":"A null result"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult":{"url":"\/documentation\/soulvercore\/evaluationresult","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Represents the underlying data of a result of a SoulverCore calculation"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EvaluationResult"}],"title":"EvaluationResult","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EvaluationResult"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/failed":{"title":"EvaluationResult.failed","kind":"symbol","url":"\/documentation\/soulvercore\/evaluationresult\/failed","abstract":[{"text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","type":"topic"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/error(_:)":{"title":"EvaluationResult.error(_:)","kind":"symbol","url":"\/documentation\/soulvercore\/evaluationresult\/error(_:)","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11SoulverCore15EvaluationErrorO","kind":"typeIdentifier","text":"EvaluationError"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)","type":"topic"}}}