{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"SoulverCore"}],"title":"EvaluationResult.failed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"externalID":"s:11SoulverCore16EvaluationResultO6failedyA2CmF","roleHeading":"Case","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore\/evaluationresult\/failed"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)"],"title":"Nil answer cases","generated":true}],"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"languages":["swift"]}]}],"abstract":[{"text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)","type":"text"}],"references":{"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult":{"type":"topic","title":"EvaluationResult","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EvaluationResult"}],"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult","navigatorTitle":[{"kind":"identifier","text":"EvaluationResult"}],"abstract":[{"type":"text","text":"Represents the underlying data of a result of a SoulverCore calculation"}],"url":"\/documentation\/soulvercore\/evaluationresult"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/failed":{"url":"\/documentation\/soulvercore\/evaluationresult\/failed","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/failed","title":"EvaluationResult.failed","abstract":[{"text":"The network could not deliver a result (perhaps due to connectivity problems or a service outage)","type":"text"}],"role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/error(_:)":{"url":"\/documentation\/soulvercore\/evaluationresult\/error(_:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11SoulverCore15EvaluationErrorO","kind":"typeIdentifier","text":"EvaluationError"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/error(_:)","title":"EvaluationResult.error(_:)","abstract":[],"role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","title":"SoulverCore","role":"collection","kind":"symbol","url":"\/documentation\/soulvercore","type":"topic","abstract":[{"text":"A powerful natural language calculation engine","type":"text"}]},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/none":{"url":"\/documentation\/soulvercore\/evaluationresult\/none","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/none","title":"EvaluationResult.none","abstract":[{"text":"A null result","type":"text"}],"role":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationResult/pending":{"url":"\/documentation\/soulvercore\/evaluationresult\/pending","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pending"}],"type":"topic","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationResult\/pending","title":"EvaluationResult.pending","abstract":[{"text":"A result that must be fetched asyncronously (probably over a network)","type":"text"}],"role":"symbol"}}}